"""Single machine-readable source for preregistered E-P1 constants."""

MODEL = "hermes3:8b"
MODEL_ID_PREFIX = "4f6b83f30b62"
MIN_OLLAMA_VERSION = (0, 30, 11)

TEMPERATURE = 0.7
TOP_P = 0.9
TOP_LOGPROBS = 5
BASE_SEED = 1337
SEED_PER_INDEX = True

K = 256
MIN_VALID_TOKENS = 32
WINDOW_SIZE = 16
MIN_SESSIONS = 5
KERNEL_TAU = 64.0
KERNEL_G_SMOOTH = 16
MARKOVIAN_BASELINE_TAU = 64.0

TEST_FRACTION = 0.25
TARGET_FPR = 0.10
PERMUTATIONS = 1000
PERMUTATION_SEED = 0
MIN_TEST_POSITIVES = 15
EXTENSION_BLOCK = 100
MAX_TOTAL_N = 1000

# Frozen by the post-pilot amendment before confirmatory collection.
FROZEN_NUM_PREDICT: int | None = None
FROZEN_PROMPT_SUITE_SHA256: str | None = None
